### PR TITLE
Change .complete to .always, as .complete has been deprecated since jQuery 1.8

### PR DESCRIPTION
**Pull request by fredngo**
This blocks upgrades to jQuery 3.0

### CODE REVIEW

**Comment by fredngo** [comment]
Thanks!

**Comment by fredngo** [comment]
@HeeL By the way could I ask you for a release to Rubygems? There probably won't be more changes in the near future, so it would be nice to have a release. Thanks!

**Comment by everaldo** [comment]
@HeeL , could you please update it on RubyGems? Thanks!

**Comment by fredngo** [comment]
@everaldo I don't have admin privileges on this gem. @HeeL is the only one that can do it. 😞

**Pull request merged**
